version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db/stasher_interview
      - TEST_DATABASE_URL=postgresql://postgres:postgres@db/stasher_interview_test
    depends_on:
      - db
    volumes:
      - .:/app
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL...'
        while ! pg_isready -h db -p 5432 -U postgres; do
          sleep 1
        done
        echo 'PostgreSQL started'
        flask db upgrade &&
        flask run --host=0.0.0.0
      "

  db:
    image: postgis/postgis:13-3.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stasher_interview
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-test-db.sh:/docker-entrypoint-initdb.d/init-test-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.track=all"

volumes:
  postgres_data:
    name: stasher_interview_postgres_data